# Generated by Django 5.1.1 on 2024-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gold_medals', models.IntegerField()),
                ('silver_medals', models.IntegerField()),
                ('bronze_medals', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('date_of_birth', models.DateField()),
                ('history', models.TextField(max_length=1000)),
            ],
        ),
    ]
