# Generated by Django 5.1.1 on 2024-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='history',
            field=models.TextField(max_length=3000),
        ),
    ]
