# Generated by Django 5.1.1 on 2024-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0002_alter_athlete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='without_bg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
