# Generated by Django 5.1.1 on 2024-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0003_athlete_without_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.URLField()),
            ],
        ),
    ]
