# Generated by Django 5.1.1 on 2024-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0004_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
